---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/notes":
    get:
      summary: notes
      parameters:
      - name: archived
        in: query
        required: false
        schema:
          type: string
      - name: search
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: list archived notes with search
    post:
      summary: Creates a note
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/note"
  "/notes/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: show note
      responses:
        '200':
          description: successful
        '404':
          description: not found
    patch:
      summary: update note
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    delete:
      summary: delete note
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
components:
  schemas:
    note:
      type: object
      required:
      - attributes
      - type
      - id
      - links
      properties:
        attributes:
          type: object
          required:
          - title
          - body
          properties:
            title:
              type: string
              example: Test title
            body:
              type: string
              example: test lorenen body
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: www.example.com
