---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/notes":
    get:
      summary: list notes
      responses:
        '200':
          description: successful
    post:
      summary: create note
      responses:
        '200':
          description: successful
  "/notes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show note
      responses:
        '200':
          description: successful
    patch:
      summary: update note
      responses:
        '200':
          description: successful
    put:
      summary: update note
      responses:
        '200':
          description: successful
    delete:
      summary: delete note
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
